version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "docker"
    directory: /docker
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "node"
        versions: ["21", "23", "25", "27", "29"]
    commit-message:
      prefix: "deps(docker)"

